name: brain2vec-torch
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - python=3.11.7
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cn2an==0.5.22
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.8
      - einops==0.7.0
      - filelock==3.13.1
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - google-auth==2.26.2
      - google-auth-oauthlib==1.2.0
      - grpcio==1.60.0
      - h5py==3.12.1
      - huggingface-hub==0.20.3
      - idna==3.6
      - jax==0.4.25
      - jaxlib==0.4.25
      - jinja2==3.1.3
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - markdown==3.5.2
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - packaging==23.2
      - pandas==2.2.0
      - pillow==10.2.0
      - pip==24.0
      - proces==0.1.7
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyparsing==3.1.1
      - pypinyin==0.51.0
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.12.25
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.4.2
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - seaborn==0.13.1
      - six==1.16.0
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.3.0
      - timm==0.9.12
      - tokenizers==0.15.2
      - torch==2.1.2
      - torch-tb-profiler==0.4.3
      - torchaudio==2.1.2
      - torchinfo==1.8.0
      - torchvision==0.16.2
      - tqdm==4.66.1
      - transformers==4.39.3
      - triton==2.1.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - urllib3==2.1.0
      - werkzeug==3.0.1
      - zhon==2.0.2
prefix: /home/norbertzheng/Documents/storage/Software/anaconda3/envs/brain2vec-torch
